In [1]:
import torch
from torch import nn
from torch import optim

In [2]:
casas_m2 = torch.tensor([[10], [13], [15], [17], [24], [28], [30], [45], [52], [64], 
                         [70], [80], [90], [100], [110], [120], [160]], 
                        dtype = torch.float32)
casas_valores = torch.tensor([[150000], [180000], [185000], [190000], [230000], [250000], [280000], [430000], [500000], 
                              [620000], [710000], [830000], [920000], [1050000], [1100000], [900000], [1300000]], 
                             dtype = torch.float32)

In [3]:
casas_m2

tensor([[ 10.],
        [ 13.],
        [ 15.],
        [ 17.],
        [ 24.],
        [ 28.],
        [ 30.],
        [ 45.],
        [ 52.],
        [ 64.],
        [ 70.],
        [ 80.],
        [ 90.],
        [100.],
        [110.],
        [120.],
        [160.]])

In [4]:
casas_valores

tensor([[ 150000.],
        [ 180000.],
        [ 185000.],
        [ 190000.],
        [ 230000.],
        [ 250000.],
        [ 280000.],
        [ 430000.],
        [ 500000.],
        [ 620000.],
        [ 710000.],
        [ 830000.],
        [ 920000.],
        [1050000.],
        [1100000.],
        [ 900000.],
        [1300000.]])

In [30]:
modelo = nn.Linear(in_features = 1, out_features = 1)
criterio = nn.MSELoss() # Mean Squared Error
otimizador = optim.SGD(modelo.parameters(), lr = 0.00001) # Stocastic Gradient Descent

In [31]:
for epoca in range(100):
    y_hat = modelo( casas_m2 )
    loss = criterio( y_hat, casas_valores )
    print(f"Epoca: {epoca}\tLoss: {loss}")
    otimizador.zero_grad()
    loss.backward()
    otimizador.step()

Epoca: 0	Loss: 470012559360.0
Epoca: 1	Loss: 373998419968.0
Epoca: 2	Loss: 297921216512.0
Epoca: 3	Loss: 237641318400.0
Epoca: 4	Loss: 189878370304.0
Epoca: 5	Loss: 152033214464.0
Epoca: 6	Loss: 122046513152.0
Epoca: 7	Loss: 98286460928.0
Epoca: 8	Loss: 79460130816.0
Epoca: 9	Loss: 64543035392.0
Epoca: 10	Loss: 52723417088.0
Epoca: 11	Loss: 43358113792.0
Epoca: 12	Loss: 35937488896.0
Epoca: 13	Loss: 30057719808.0
Epoca: 14	Loss: 25398863872.0
Epoca: 15	Loss: 21707407360.0
Epoca: 16	Loss: 18782457856.0
Epoca: 17	Loss: 16464871424.0
Epoca: 18	Loss: 14628514816.0
Epoca: 19	Loss: 13173468160.0
Epoca: 20	Loss: 12020558848.0
Epoca: 21	Loss: 11107041280.0
Epoca: 22	Loss: 10383206400.0
Epoca: 23	Loss: 9809673216.0
Epoca: 24	Loss: 9355223040.0
Epoca: 25	Loss: 8995138560.0
Epoca: 26	Loss: 8709816320.0
Epoca: 27	Loss: 8483739136.0
Epoca: 28	Loss: 8304600576.0
Epoca: 29	Loss: 8162654208.0
Epoca: 30	Loss: 8050177024.0
Epoca: 31	Loss: 7961051648.0
Epoca: 32	Loss: 7890432512.0
Epoca: 33	Loss: 7834468

In [32]:
modelo.weight

Parameter containing:
tensor([[9173.8125]], requires_grad=True)

In [33]:
modelo.bias

Parameter containing:
tensor([147.1527], requires_grad=True)

In [35]:
modelo( torch.tensor([ [100.0] ]) )

tensor([[917528.3750]], grad_fn=<AddmmBackward0>)