In [1]:
import pandas as pd

In [2]:
import torch
from torch import nn, optim

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("D:/git/dados/nlp/news_sentiment_analysis.csv", encoding="utf-8")

In [5]:
df = df[["Description", "Sentiment"]]

In [9]:
df["sentiment_number"] = df["Sentiment"].map( {"positive": 1, "negative": 0, "neutral": 0} )

C:\Users\anton\AppData\Local\Temp\ipykernel_34988\1331602582.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sentiment_number"] = df["Sentiment"].map( {"positive": 1, "negative": 0, "neutral": 0} )


In [13]:
Y = torch.tensor(df["sentiment_number"], dtype=torch.float32)
Y = torch.reshape( Y, (-1, 1) )
Y

tensor([[1.],
        [0.],
        [1.],
        ...,
        [1.],
        [0.],
        [1.]])

In [31]:
vetorizador = CountVectorizer(max_features = 1000)

In [32]:
X = vetorizador.fit_transform( df["Description"] )
X = torch.tensor(X.toarray(), dtype=torch.float32)
X

tensor([[0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])

In [33]:
vocabulario = vetorizador.get_feature_names_out()

In [51]:
modelo = nn.Sequential(
    nn.Linear(in_features = 1000, out_features = 1), 
    nn.Sigmoid()
)
otimizador = optim.SGD( modelo.parameters(), lr=1)
criterio = nn.BCELoss() # Binary Cross Entropy Perda

In [52]:
for epoca in range(1000):
    y_hat = modelo( X ) 
    loss = criterio( y_hat, Y )
    print(f"Loss: {loss}")
    otimizador.zero_grad()
    loss.backward()
    otimizador.step()

Loss: 0.6935198903083801
Loss: 0.8987799882888794
Loss: 0.67508864402771
Loss: 0.9761919379234314
Loss: 0.5606048703193665
Loss: 0.6211598515510559
Loss: 0.6439062356948853
Loss: 0.9107714891433716
Loss: 0.5188058614730835
Loss: 0.5466120839118958
Loss: 0.5592908263206482
Loss: 0.6953540444374084
Loss: 0.5448324084281921
Loss: 0.6556451320648193
Loss: 0.5316104888916016
Loss: 0.6245814561843872
Loss: 0.51976078748703
Loss: 0.5998441576957703
Loss: 0.5094355940818787
Loss: 0.5801630616188049
Loss: 0.5002450346946716
Loss: 0.5636940598487854
Loss: 0.4919630289077759
Loss: 0.5495104789733887
Loss: 0.4843912124633789
Loss: 0.5369696617126465
Loss: 0.47739335894584656
Loss: 0.5256776809692383
Loss: 0.47086936235427856
Loss: 0.5153705477714539
Loss: 0.4647457003593445
Loss: 0.5058656334877014
Loss: 0.4589659869670868
Loss: 0.497029572725296
Loss: 0.45348602533340454
Loss: 0.4887624979019165
Loss: 0.4482702910900116
Loss: 0.4809871315956116
Loss: 0.4432896673679352
Loss: 0.47364217042922974
L

In [65]:
texto =  "trade war occurs in all world, causing faminy and disgrace" # df["Description"][900]
# resultado = df["sentiment_number"][900]
# print(f"Resultado: {resultado}\t\tDescricao: {texto}")

In [66]:
vetorizador_teste = CountVectorizer( vocabulary = vocabulario )

In [67]:
X_teste = vetorizador_teste.fit_transform( [texto] )
X_teste = torch.tensor( [X_teste.toarray()], dtype=torch.float32 )
X_teste

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [68]:
Y_hat_teste = modelo( X_teste )
Y_hat_teste.item()

0.41593316197395325