In [2]:
import torch

In [3]:
t10 = torch.tensor( 10 )
t10

tensor(10)

In [7]:
print("Shape: ", t10.shape)
print("Dimensoes: ", t10.ndim)
print("Tipo de dado: ", t10.dtype)

Shape:  torch.Size([])
Dimensoes:  0
Tipo de dado:  torch.int64


In [8]:
v3 = torch.tensor( [2.0, 3.0, 6.0] )
v3

tensor([2., 3., 6.])

In [9]:
print("Shape: ", v3.shape)
print("Dimensoes: ", v3.ndim)
print("Tipo de dado: ", v3.dtype)

Shape:  torch.Size([3])
Dimensoes:  1
Tipo de dado:  torch.float32


In [10]:
m3 = torch.rand([3, 4, 5])
m3

tensor([[[0.5276, 0.0802, 0.6875, 0.4574, 0.7247],
         [0.3924, 0.8911, 0.3566, 0.8694, 0.2482],
         [0.3084, 0.4205, 0.2220, 0.3843, 0.4428],
         [0.9957, 0.2221, 0.9406, 0.4092, 0.8875]],

        [[0.4235, 0.8584, 0.4061, 0.4628, 0.6008],
         [0.4054, 0.6748, 0.4051, 0.4438, 0.8891],
         [0.1717, 0.3480, 0.8883, 0.6319, 0.3784],
         [0.0485, 0.6908, 0.7819, 0.8432, 0.3327]],

        [[0.2499, 0.1708, 0.2629, 0.7257, 0.2012],
         [0.1985, 0.6052, 0.1919, 0.6726, 0.5643],
         [0.3301, 0.1770, 0.5909, 0.2973, 0.7270],
         [0.5708, 0.2875, 0.9297, 0.8924, 0.6323]]])

In [11]:
print("Shape: ", m3.shape)
print("Dimensoes: ", m3.ndim)
print("Tipo de dado: ", m3.dtype)

Shape:  torch.Size([3, 4, 5])
Dimensoes:  3
Tipo de dado:  torch.float32


In [12]:
torch.cuda.is_available()

True

In [14]:
m3.to("cuda")

tensor([[[0.5276, 0.0802, 0.6875, 0.4574, 0.7247],
         [0.3924, 0.8911, 0.3566, 0.8694, 0.2482],
         [0.3084, 0.4205, 0.2220, 0.3843, 0.4428],
         [0.9957, 0.2221, 0.9406, 0.4092, 0.8875]],

        [[0.4235, 0.8584, 0.4061, 0.4628, 0.6008],
         [0.4054, 0.6748, 0.4051, 0.4438, 0.8891],
         [0.1717, 0.3480, 0.8883, 0.6319, 0.3784],
         [0.0485, 0.6908, 0.7819, 0.8432, 0.3327]],

        [[0.2499, 0.1708, 0.2629, 0.7257, 0.2012],
         [0.1985, 0.6052, 0.1919, 0.6726, 0.5643],
         [0.3301, 0.1770, 0.5909, 0.2973, 0.7270],
         [0.5708, 0.2875, 0.9297, 0.8924, 0.6323]]], device='cuda:0')

In [16]:
v3 + m3

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 2

In [19]:
m4 = m3.clone()

In [20]:
m4.to("cpu")

tensor([[[0.5276, 0.0802, 0.6875, 0.4574, 0.7247],
         [0.3924, 0.8911, 0.3566, 0.8694, 0.2482],
         [0.3084, 0.4205, 0.2220, 0.3843, 0.4428],
         [0.9957, 0.2221, 0.9406, 0.4092, 0.8875]],

        [[0.4235, 0.8584, 0.4061, 0.4628, 0.6008],
         [0.4054, 0.6748, 0.4051, 0.4438, 0.8891],
         [0.1717, 0.3480, 0.8883, 0.6319, 0.3784],
         [0.0485, 0.6908, 0.7819, 0.8432, 0.3327]],

        [[0.2499, 0.1708, 0.2629, 0.7257, 0.2012],
         [0.1985, 0.6052, 0.1919, 0.6726, 0.5643],
         [0.3301, 0.1770, 0.5909, 0.2973, 0.7270],
         [0.5708, 0.2875, 0.9297, 0.8924, 0.6323]]])

In [21]:
m3

tensor([[[0.5276, 0.0802, 0.6875, 0.4574, 0.7247],
         [0.3924, 0.8911, 0.3566, 0.8694, 0.2482],
         [0.3084, 0.4205, 0.2220, 0.3843, 0.4428],
         [0.9957, 0.2221, 0.9406, 0.4092, 0.8875]],

        [[0.4235, 0.8584, 0.4061, 0.4628, 0.6008],
         [0.4054, 0.6748, 0.4051, 0.4438, 0.8891],
         [0.1717, 0.3480, 0.8883, 0.6319, 0.3784],
         [0.0485, 0.6908, 0.7819, 0.8432, 0.3327]],

        [[0.2499, 0.1708, 0.2629, 0.7257, 0.2012],
         [0.1985, 0.6052, 0.1919, 0.6726, 0.5643],
         [0.3301, 0.1770, 0.5909, 0.2973, 0.7270],
         [0.5708, 0.2875, 0.9297, 0.8924, 0.6323]]])

In [22]:
m4

tensor([[[0.5276, 0.0802, 0.6875, 0.4574, 0.7247],
         [0.3924, 0.8911, 0.3566, 0.8694, 0.2482],
         [0.3084, 0.4205, 0.2220, 0.3843, 0.4428],
         [0.9957, 0.2221, 0.9406, 0.4092, 0.8875]],

        [[0.4235, 0.8584, 0.4061, 0.4628, 0.6008],
         [0.4054, 0.6748, 0.4051, 0.4438, 0.8891],
         [0.1717, 0.3480, 0.8883, 0.6319, 0.3784],
         [0.0485, 0.6908, 0.7819, 0.8432, 0.3327]],

        [[0.2499, 0.1708, 0.2629, 0.7257, 0.2012],
         [0.1985, 0.6052, 0.1919, 0.6726, 0.5643],
         [0.3301, 0.1770, 0.5909, 0.2973, 0.7270],
         [0.5708, 0.2875, 0.9297, 0.8924, 0.6323]]])

In [23]:
m3 + m4

tensor([[[1.0552, 0.1604, 1.3750, 0.9147, 1.4495],
         [0.7847, 1.7821, 0.7132, 1.7387, 0.4964],
         [0.6167, 0.8411, 0.4441, 0.7687, 0.8855],
         [1.9913, 0.4442, 1.8812, 0.8184, 1.7750]],

        [[0.8469, 1.7167, 0.8121, 0.9256, 1.2017],
         [0.8109, 1.3495, 0.8102, 0.8877, 1.7783],
         [0.3434, 0.6961, 1.7767, 1.2638, 0.7568],
         [0.0969, 1.3816, 1.5638, 1.6863, 0.6653]],

        [[0.4998, 0.3416, 0.5257, 1.4514, 0.4025],
         [0.3971, 1.2104, 0.3837, 1.3451, 1.1286],
         [0.6603, 0.3540, 1.1818, 0.5947, 1.4540],
         [1.1416, 0.5750, 1.8593, 1.7849, 1.2646]]])

In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [25]:
torch.device( device ) 

device(type='cuda')

In [26]:
m3 + m4

tensor([[[1.0552, 0.1604, 1.3750, 0.9147, 1.4495],
         [0.7847, 1.7821, 0.7132, 1.7387, 0.4964],
         [0.6167, 0.8411, 0.4441, 0.7687, 0.8855],
         [1.9913, 0.4442, 1.8812, 0.8184, 1.7750]],

        [[0.8469, 1.7167, 0.8121, 0.9256, 1.2017],
         [0.8109, 1.3495, 0.8102, 0.8877, 1.7783],
         [0.3434, 0.6961, 1.7767, 1.2638, 0.7568],
         [0.0969, 1.3816, 1.5638, 1.6863, 0.6653]],

        [[0.4998, 0.3416, 0.5257, 1.4514, 0.4025],
         [0.3971, 1.2104, 0.3837, 1.3451, 1.1286],
         [0.6603, 0.3540, 1.1818, 0.5947, 1.4540],
         [1.1416, 0.5750, 1.8593, 1.7849, 1.2646]]])

In [32]:
n1 = torch.tensor( 100.0, requires_grad = True) 

In [33]:
y_hat = n1 ** 8

In [34]:
y_hat.backward()

In [36]:
n1.grad

tensor(8.0000e+14)